apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: quiz
  labels:
    app: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa # Bind to a specific service account for RBAC
      automountServiceAccountToken: false # Disable automatic service account token mounting
      containers:
      - name: frontend
        image: shantanu789/frontend-js # Use a specific version tag
        env:
        - name: VITE_REACT_APP_API_URL
          value: "http://quizapp.campixart.com/api/questions"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m" # CPU request
            memory: "256Mi" # Memory request.
          limits:
            cpu: "400m" # CPU limit
            memory: "512Mi" # Memory limit
        volumeMounts:
        - name: frontend-storage
          mountPath: /data/storage # Adjust mount path as needed
      volumes:
      - name: frontend-storage
        persistentVolumeClaim:
          claimName: frontend-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
  namespace: quiz
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # Storage request for PVC
    limits:
      storage: 1Gi # Storage limit for PVC
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: quiz
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: quiz
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-role
  namespace: quiz
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-role-binding
  namespace: quiz
subjects:
- kind: ServiceAccount
  name: frontend-sa
  namespace: quiz
roleRef:
  kind: Role
  name: frontend-role
  apiGroup: rbac.authorization.k8s.io